// 提案カードDB（知識ベース data/knowledge_base.md から生成）
// applies: 該当する {sex, ageBand, goal}。"all" は全該当。
// evidence: 信頼度 1-3 (★)。priority: 採用優先度 1-5。
// 方針: 検査/器材なし・スーパー食材・iHerbサプリ・自宅運動・継続重視。
window.YOBOU_CARDS = [
  // ===== 食事 diet =====
  { id:"diet-bloodsugar", domain:"diet", title:"血糖を乱高下させない食べ方",
    body:"野菜・きのこ・海藻などの食物繊維、次にタンパク質、最後に炭水化物の順で食べる。白い炭水化物(白米・食パン・うどん)は玄米・全粒粉・そばなど茶色いものへ。血糖スパイク=糖化(老化・肌荒れ・だるさ)を防ぐ。",
    applies:{sex:["male","female"], ageBand:"all", goal:["fatloss","longevity","energy"]}, priority:5, evidence:3, source:"hii1VzgEcQU / advanced_system" },
  { id:"diet-3meals", domain:"diet", title:"1日3食・トータルで整える",
    body:"夜にドカ食いする1食より、3食に分けて時間を一定にする方が血糖・ホルモンが安定。夜が多くなる日は朝昼で野菜・魚・食物繊維を補い、1日の合計で帳尻を合わせる。",
    applies:{sex:["male","female"], ageBand:"all", goal:["fatloss","longevity","energy"]}, priority:4, evidence:3, source:"IM6bt5mzbi4" },
  { id:"diet-mediterranean", domain:"diet", title:"地中海食ベースにする",
    body:"野菜・果物を皿の半分。タンパク質は肉より魚(青魚=EPA/DHA)、肉は赤身より鶏・豚。豆類を活用。塩の代わりにスパイスや酸味。良い油(オリーブオイル・青魚・くるみ・アボカド)を、悪い油(揚げ物・脂身)は控える。",
    applies:{sex:["male","female"], ageBand:"all", goal:["longevity","fatloss","energy"]}, priority:5, evidence:3, source:"2tKWNAPqC3U / spartan_testosterone" },
  { id:"diet-protein", domain:"diet", title:"タンパク質を毎食に",
    body:"目安は1日で体重(kg)+20%程度のg数。例) 70kg→約80g。卵・納豆・豆腐は各約7g、魚定食で約20g。麺類単体は不足しがちなので一品足す。植物性は動物性の約半分の吸収効率なので偏らない。",
    applies:{sex:["male","female"], ageBand:"all", goal:["muscle","fatloss","energy"]}, priority:5, evidence:3, source:"2tKWNAPqC3U" },
  { id:"diet-iron", domain:"diet", title:"鉄分でミトコンドリアを元気に",
    body:"鉄はエネルギー産生(ミトコンドリア)に直結。赤身肉・レバー・ほうれん草・青魚を意識して摂る。疲れやすい人ほど重要。",
    applies:{sex:["male","female"], ageBand:"all", goal:["energy"]}, priority:4, evidence:2, source:"jRA_7Q53VRE" },
  { id:"diet-gut", domain:"diet", title:"腸内環境を育てる発酵性食物繊維",
    body:"善玉菌の餌=オリゴ糖(玉ねぎ・ごぼう・ねぎ・アスパラ・豆・さつまいも)。ぬるぬる系の水溶性食物繊維(もずく・めかぶ・わかめ)を意識(不溶性と2:1が目安)。味噌・納豆など発酵食品も。",
    applies:{sex:["male","female"], ageBand:"all", goal:["longevity","energy"]}, priority:3, evidence:2, source:"2tKWNAPqC3U / _PdOdgnRVyg" },
  { id:"diet-processed", domain:"diet", title:"超加工食品・添加物を減らす",
    body:"お菓子やインスタントは小分けで買い、家にストックしない。完全にやめなくても『10回のうち3回をナッツ・果物・ヨーグルトに置き換える』だけで効果。",
    applies:{sex:["male","female"], ageBand:"all", goal:["fatloss","longevity"]}, priority:3, evidence:2, source:"IM6bt5mzbi4" },
  { id:"diet-women-iron", domain:"diet", title:"女性は鉄分を特に意識",
    body:"月経で鉄が失われやすく、月経中は鉄が最も低下する。赤身肉・レバー・あさり・ほうれん草＋ビタミンC(柑橘・ピーマン)で吸収アップ。だるさ・冷え対策にも。",
    applies:{sex:["female"], ageBand:"all", goal:["energy","longevity","fatloss","muscle"]}, priority:4, evidence:3, source:"PMC12681887 / PMC10538277" },
  { id:"diet-women-luteal", domain:"diet", title:"生理前(黄体期)のPMS対策",
    body:"排卵後〜生理前はPMSが出やすい時期。マグネシウム(ナッツ・海藻・豆)とカルシウム(乳製品・小魚・豆腐)が役立つ(Cochraneレビュー)。甘い物が欲しくなるので食物繊維とタンパク質で血糖を安定させると楽に。",
    applies:{sex:["female"], ageBand:["20s","30s","40s"], goal:["energy","fatloss","longevity"]}, priority:3, evidence:3, source:"Cochrane 2023" },
  { id:"diet-women-menopause", domain:"diet", title:"更年期は骨と大豆を意識",
    body:"40代後半〜は骨密度が下がりやすい。カルシウム＋ビタミンD＋ビタミンK2を食事で(小魚・乳製品・大豆・きのこ＋日光)。ホットフラッシュには大豆食品(豆腐・納豆・枝豆)を食事から。地中海食は血圧・中性脂肪にも有効。",
    applies:{sex:["female"], ageBand:["40s","50s","60s"], goal:["longevity","energy","fatloss"]}, priority:4, evidence:3, source:"Frontiers 2025 / NAMS" },

  { id:"diet-eat-order", domain:"diet", title:"満腹サインを働かせる食べ方",
    body:"食物繊維→タンパク質→炭水化物の順で食べると満腹感が早く出て食べ過ぎ防止。タンパク質と青魚(オメガ3)は満腹ホルモンを出す。規則的な食事時間にすると空腹も予測しやすく管理が楽に。",
    applies:{sex:["male","female"], ageBand:"all", goal:["fatloss","longevity","energy"]}, priority:4, evidence:3, source:"HUB#136" },
  { id:"diet-walk-meal", domain:"diet", title:"食後に軽く歩く",
    body:"食前・食後の軽い散歩(10分でも)で血糖の急上昇がゆるやかに。食器を片付けながら、近所を一周でOK。眠気やだるさも減る。",
    applies:{sex:["male","female"], ageBand:"all", goal:["fatloss","energy","longevity"]}, priority:3, evidence:3, source:"HUB#136" },

  // ===== 運動 exercise =====
  { id:"ex-interval-walk", domain:"exercise", title:"インターバル速歩",
    body:"速歩3分・ゆっくり3分を交互に5セット(計30分)。器具不要・自宅周辺でOK。ミトコンドリア活性で疲れにくい体に。週2回から。",
    applies:{sex:["male","female"], ageBand:"all", goal:["energy","fatloss","longevity"]}, priority:5, evidence:3, source:"jRA_7Q53VRE" },
  { id:"ex-squat", domain:"exercise", title:"自重スクワット",
    body:"足を肩幅、椅子に座るように腰を落とし3秒かけて下ろす→立つ。10〜15回×2〜3セット。下半身は最大の筋肉。男性はテストステロン維持にも有効。",
    applies:{sex:["male","female"], ageBand:"all", goal:["muscle","energy","longevity"]}, priority:5, evidence:3, source:"spartan_testosterone / hii1VzgEcQU" },
  { id:"ex-shiko", domain:"exercise", title:"四股(しこ)10回",
    body:"足を肩幅の1.5〜2倍、腰を深く落として肛門を締める。片足に体重を乗せ、反動を使わず3秒かけて下ろす。左右交互で10回。骨盤底筋・体幹・バランス・腰痛予防に。",
    applies:{sex:["male","female"], ageBand:["30s","40s","50s","60s"], goal:["muscle","energy","longevity"]}, priority:4, evidence:2, source:"vn4TLSlqd0s" },
  { id:"ex-strength-intensity", domain:"exercise", title:"筋トレは強度×短い休憩で",
    body:"筋肥大とテストステロンには『限界近くまで×短い休憩(2分)×十分な量』が効く。自宅では片足スクワットなどキツい自重種目で代替。きつい日は週2回、他の日は高回数(15〜20回)で刺激を変える。女性も筋トレでホルモン・骨に好影響。",
    applies:{sex:["male","female"], ageBand:"all", goal:["muscle","energy"]}, priority:4, evidence:3, source:"HUB#77" },
  { id:"ex-zone2", domain:"exercise", title:"ゾーン2有酸素で血糖安定",
    body:"会話できる/鼻呼吸できる軽めの強度(早歩き・ジョグ・自転車)を30〜60分、週3〜4回。インスリン感受性が上がり血糖が安定、脂肪も使いやすい体に。",
    applies:{sex:["male","female"], ageBand:"all", goal:["fatloss","energy","longevity"]}, priority:4, evidence:3, source:"HUB#136" },
  { id:"ex-not-too-much", domain:"exercise", title:"やり過ぎない(質>量)",
    body:"筋トレは週2〜3回・1回30分未満で十分。やり過ぎはコルチゾール上昇で逆効果。有酸素もやり過ぎると筋分解。回復日を必ず入れる。",
    applies:{sex:["male","female"], ageBand:"all", goal:["muscle","energy","longevity"]}, priority:4, evidence:3, source:"hii1VzgEcQU / growth_hormone" },
  { id:"ex-bodyweight-circuit", domain:"exercise", title:"自重サーキット(減量向け)",
    body:"スクワット→腕立て(膝つきOK)→プランク30秒→もも上げ、を休憩短めで2〜3周。器具なしで脂肪燃焼+筋維持。週2〜3回。",
    applies:{sex:["male","female"], ageBand:["20s","30s","40s"], goal:["fatloss"]}, priority:4, evidence:2, source:"knowledge_base" },
  { id:"ex-women-cycle", domain:"exercise", title:"周期に合わせた運動(女性)",
    body:"生理後〜排卵(卵胞期)は筋肉がつきやすく力も出やすいので、筋トレや強めの運動をこの時期に。排卵後〜生理前(黄体期)や月経中は無理せず、速歩・ヨガ・ストレッチなど軽めに切り替えると続けやすい。",
    applies:{sex:["female"], ageBand:["20s","30s","40s"], goal:["muscle","fatloss","energy","longevity"]}, priority:3, evidence:2, source:"PMC10538277" },
  { id:"ex-mobility", domain:"exercise", title:"柔軟・関節ケア",
    body:"40代以降は関節・柔軟性が低下。運動前後に股関節・肩・背中を各30秒ストレッチ。転倒・ケガ予防に。",
    applies:{sex:["male","female"], ageBand:["40s","50s","60s"], goal:["longevity","energy"]}, priority:3, evidence:2, source:"knowledge_base" },
  { id:"ex-timing", domain:"exercise", title:"運動のタイミングと睡眠",
    body:"朝は軽い有酸素20〜30分で夜の睡眠が改善。強度の高い運動は就寝3〜4時間前までに終える(22時就寝なら19時まで)。",
    applies:{sex:["male","female"], ageBand:"all", goal:["energy","longevity","fatloss"]}, priority:3, evidence:3, source:"BL#940 (Alan Aragon)" },

  // ===== 睡眠 sleep =====
  { id:"sleep-core", domain:"sleep", title:"睡眠はホルモンの最大スイッチ",
    body:"深睡眠中に成長ホルモンとテストステロンが出てミトコンドリアを修復。6〜8時間、中途覚醒・夜間トイレを避けて熟睡を。翌日の体力が変わる。",
    applies:{sex:["male","female"], ageBand:"all", goal:["energy","muscle","longevity"]}, priority:5, evidence:3, source:"jRA_7Q53VRE / growth_hormone" },
  { id:"sleep-evening", domain:"sleep", title:"就寝前の食事・飲酒を控える",
    body:"遅い時間の食事や酒は深部体温・心拍・血圧を上げ睡眠を浅くする。夕食は就寝3時間前まで。夜の炭水化物は適量だと中途覚醒が減る。",
    applies:{sex:["male","female"], ageBand:"all", goal:["energy","longevity","fatloss"]}, priority:4, evidence:3, source:"IM6bt5mzbi4 / BL#940" },
  { id:"sleep-dinner", domain:"sleep", title:"睡眠を良くする夕食の組み立て",
    body:"夕食の飽和脂肪は控えめ(摂りすぎ=寝汗で睡眠分断)。食物繊維(温野菜・サラダ)とオメガ3(青魚)で睡眠の質アップ。タンパク質はメラトニンの材料に。",
    applies:{sex:["male","female"], ageBand:"all", goal:["energy","longevity"]}, priority:3, evidence:3, source:"BL#940 (Alan Aragon)" },

  // ===== 休息 rest =====
  { id:"rest-stress", domain:"rest", title:"ストレス=コルチゾール管理",
    body:"慢性ストレスはコルチゾール過剰→ミトコンドリア低下→疲労。意識的に休む時間を作る。高すぎても低すぎてもダメで『ちょうどいい』を保つ。",
    applies:{sex:["male","female"], ageBand:"all", goal:["energy","longevity"]}, priority:4, evidence:2, source:"jRA_7Q53VRE" },
  { id:"rest-heat", domain:"rest", title:"サウナ・入浴で回復",
    body:"熱刺激は成長ホルモン分泌と血流改善に有効。週末はサウナやぬるめの入浴で体温を上げ、リラックス。体温36.5℃以上の維持も目安。",
    applies:{sex:["male","female"], ageBand:"all", goal:["energy","longevity","muscle"]}, priority:3, evidence:2, source:"growth_hormone / _PdOdgnRVyg" },
  { id:"rest-chew", domain:"rest", title:"よく噛む・口腔ケア",
    body:"よく噛むと自律神経が整う。舌の汚れ(舌苔)を落とし、口の中を清潔に。口腔→腸→全身に影響。地味だが効く習慣。",
    applies:{sex:["male","female"], ageBand:"all", goal:["longevity","energy"]}, priority:2, evidence:2, source:"_PdOdgnRVyg / hii1VzgEcQU" },
  { id:"rest-cold-timing", domain:"rest", title:"筋トレ直後の冷水は控える",
    body:"筋肉を大きくしたい時期は運動直後のアイスバス/冷水を避ける(炎症=成長シグナルを鈍らせる)。サウナや温浴での回復を。冷却は試合前など別目的の時に。",
    applies:{sex:["male","female"], ageBand:"all", goal:["muscle"]}, priority:2, evidence:2, source:"HUB#77" },
  { id:"rest-restday", domain:"rest", title:"週に2日は積極的休養",
    body:"完全に動かないより、軽い散歩・ストレッチなど低強度で体をほぐす。回復こそが成長と疲労抜きの本番。",
    applies:{sex:["male","female"], ageBand:"all", goal:["muscle","energy","longevity","fatloss"]}, priority:3, evidence:2, source:"knowledge_base" },

  // ===== 瞑想・呼吸 meditation =====
  { id:"med-box", domain:"meditation", title:"ボックス呼吸 5分",
    body:"4秒吸う→4秒止める→4秒吐く→4秒止める、を5分繰り返す。自律神経を整え、ストレス・緊張をリセット。夕方や寝る前に。",
    applies:{sex:["male","female"], ageBand:"all", goal:["energy","longevity"]}, priority:4, evidence:2, source:"knowledge_base (要Podcast補強)" },
  { id:"med-sigh", domain:"meditation", title:"生理的ためいきで即リセット",
    body:"鼻から吸う→さらに鼻から短く吸い足す(二段吸い)→口から長く吐ききる。これを1〜3回。数十秒で心拍が落ち着きストレスが下がる。会議前やイライラ時に。『吐く息を長く』が落ち着くコツ。",
    applies:{sex:["male","female"], ageBand:"all", goal:["energy","longevity","fatloss","muscle"]}, priority:4, evidence:3, source:"HUB#60 (Feldman博士)" },
  { id:"med-morning", domain:"meditation", title:"朝の3分マインドフルネス",
    body:"座って目を閉じ、呼吸の感覚にだけ注意を向ける。考えが浮かんだら呼吸に戻す。3分でOK。1日の集中力と気分が安定。",
    applies:{sex:["male","female"], ageBand:"all", goal:["energy","longevity","fatloss","muscle"]}, priority:3, evidence:2, source:"knowledge_base (要Podcast補強)" },
  { id:"med-meal", domain:"meditation", title:"楽しく食べる",
    body:"地中海食ピラミッドの最上位は『誰と楽しく食べるか』。スマホを置いて味わう。日中ちゃんと動いて空腹で食べると満足度も健康効果も上がる。",
    applies:{sex:["male","female"], ageBand:"all", goal:["longevity","fatloss"]}, priority:2, evidence:2, source:"2tKWNAPqC3U" },

  // ===== サプリ supplement (iHerb等で入手可) =====
  { id:"supp-omega3", domain:"supplement", title:"オメガ3(フィッシュオイル)",
    body:"青魚を食べられない日に。炎症ケア・睡眠・心血管に。iHerbでEPA/DHA高配合のものを。食事を基本に、あくまで補助。",
    applies:{sex:["male","female"], ageBand:"all", goal:["longevity","energy","muscle"]}, priority:3, evidence:2, source:"BL#940 / 2tKWNAPqC3U" },
  { id:"supp-mag", domain:"supplement", title:"マグネシウム",
    body:"睡眠・筋肉の弛緩・ストレスに関与。不足しがち。グリシン酸マグネシウムが胃にやさしい。就寝前に。",
    applies:{sex:["male","female"], ageBand:"all", goal:["energy","longevity"]}, priority:3, evidence:2, source:"BL#940" },
  { id:"supp-vitd", domain:"supplement", title:"ビタミンD",
    body:"日照不足だと不足しやすく睡眠・免疫に影響。iHerbでD3(+K2)を。まずは日光を浴びるのが基本。",
    applies:{sex:["male","female"], ageBand:"all", goal:["longevity","energy"]}, priority:3, evidence:2, source:"BL#940" },
  { id:"supp-women-cal", domain:"supplement", title:"女性: カルシウム+ビタミンD(骨)",
    body:"閉経後は骨密度低下に注意。目安はカルシウム約1200mg・ビタミンD 800〜1000IU/日。乳製品・小魚・大豆＋日光を基本に、不足分をサプリ(D3+K2)で。",
    applies:{sex:["female"], ageBand:["40s","50s","60s"], goal:["longevity","energy"]}, priority:3, evidence:3, source:"Frontiers 2025 / 骨粗鬆症レビュー" },
  { id:"supp-women-mag", domain:"supplement", title:"女性: マグネシウム(PMS)",
    body:"マグネシウムは生理前の不調(PMS)緩和に役立つ(Cochrane)。まずはナッツ・海藻・豆・葉物から。不足しがちなのでグリシン酸マグネシウムを就寝前に補うのも手。",
    applies:{sex:["female"], ageBand:["20s","30s","40s"], goal:["energy","longevity","fatloss"]}, priority:3, evidence:2, source:"Cochrane 2023" },
  { id:"supp-men-zinc", domain:"supplement", title:"男性: 亜鉛",
    body:"テストステロン・免疫に関与し不足しがち。牡蠣・赤身肉が基本。摂りすぎ注意(銅とのバランス)。iHerbで適量を。",
    applies:{sex:["male"], ageBand:["30s","40s","50s","60s"], goal:["muscle","energy","longevity"]}, priority:3, evidence:2, source:"spartan_testosterone" }
];
